#!/bin/bash

#Do que será feito o backup
PREFIXODIR='/home/gabriel/Documents/Camisetas'
BACKUPDIR='.backup'
BACKUP="*/Prontas modelo_camiseta.svg"

#Nome dos arquivos
PREFIXO=backup-
DATA=`date +%Y%m%d-%H%M%S`
NOME=$PREFIXO$DATA.tar.bz2
ULTIMO=`ls $PREFIXODIR/$PREFIXO*`

#Informações para envio do e-mail
EMAIL='gabrielmcf@gmail.com'
ATTACH="/home/gabriel/Documents/Camisetas/$NOME"
SUBJECT="Backup Camisas"

#Arquivo de log
LOG="/var/log/backup.log"

#Função ajuda
ajuda(){

echo ""
echo "Uso:"
echo "	`basename $0` [OPÇÃO] - Realiza o backup dos arquivos configurados no script."
echo "Opções:"
echo "	-f	Força a realização do backup independente de modificação ou não;"
echo "	-h	Exibe esse help."
echo ""
echo "Script desenvolvido por Gabriel Fonseca sobre a licença Beerware."
echo ""
}

#Função de log
log_backup(){

echo "[$DATA] Backup feito por $USER. MD5: $1" >> $LOG

}

#Função cria tar
cria_tar(){
	
	tar -cvjf $NOME $BACKUPDIR/*

	MD5=`md5sum $NOME`

	log_backup "$MD5";

}

#Função manda e-mail
manda_email(){

	evolution mailto:$EMAIL?body="$MD5"\&subject="$SUBJECT"\&attach="$ATTACH" &

}


##################
#Começo do script#
##################

if [ "$1" = "-h" ]; then
ajuda;
exit 0;
fi

cd $PREFIXODIR

rm -f aux

for i in `ls -d $BACKUP`; do

	if [ -d $i ]; then
		mkdir -p $BACKUPDIR/$i
		rsync -iba $i/ $BACKUPDIR/$i >> aux
	else
		rsync -iba $i $BACKUPDIR >> aux
	fi

done

if [ -s aux -o "$1" = "-f" ]; then
	cria_tar;
	rm $ULTIMO aux
	manda_email;
	exit 0;
fi

if [ -z "$ULTIMO"  ]; then
	cria_tar;
	rm $ULTIMO aux
	manda_email;
	exit 0;
fi

echo "O último backup já é o mais atual!"

rm -f aux













